"""Generates Skins/AIStockNews/Watchlist/Watchlist.ini.

Rainmeter cannot create meters at runtime, so the skin declares one block of
meters per tile. Edit this script instead of the .ini, then run:

    python tools/generate_watchlist_skin.py
"""

from __future__ import annotations

import sys
from pathlib import Path

MAX_TILES = 12
OUTPUT = (
    Path(__file__).resolve().parents[1] / "Skins" / "AIStockNews" / "Watchlist" / "Watchlist.ini"
)

HEADER = """\
; AI Stock News - Watchlist: live prices and charts for your own tickers.
; GENERATED by tools/generate_watchlist_skin.py. Edit that script, not this file.
; Appearance: @Resources\\Variables.inc. Tickers: the + button, the x on a tile,
; or [tracker] tickers in config.ini (right-click > Edit settings).

[Rainmeter]
Update=1000
AccurateText=1
DynamicWindowSize=1
ContextTitle=Add stocks
ContextAction=[!CommandMeasure MeasureAddInput "ExecuteBatch 1"]
ContextTitle2=Refresh now
ContextAction2=[!CommandMeasure MeasureScript "RefreshNow()"]
ContextTitle3=Edit settings (tickers, API keys)
ContextAction3=[!CommandMeasure MeasureOpenConfig "Run"]
ContextTitle4=Edit appearance
ContextAction4=["#CONFIGEDITOR#" "#@#Variables.inc"]
ContextTitle5=Open log
ContextAction5=["#CONFIGEDITOR#" "#@#data\\watchlist.log"]

[Metadata]
Name=AI Stock News - Watchlist
Author=gstarr96
Information=A grid of your own tickers with live price, % and point change, and an intraday chart behind each tile. Uses Yahoo Finance only, no AI calls.
Version=0.2.0
License=MIT

[Variables]
@Include=#@#Variables.inc
WatchMaxTiles={max_tiles}
SkinW=(#Padding# * 2 + #WatchColumns# * #WatchTileW# + (#WatchColumns# - 1) * #WatchGap#)
GridY=(#Padding# + 24)
BackendCommand=-B "#@#backend\\run.py"
NewTickers=
{tile_variables}
; ============================================================ Measures

[MeasureScript]
Measure=Script
ScriptFile=#@#Scripts\\Watchlist.lua

[MeasureTracker]
Measure=Plugin
Plugin=RunCommand
Program=#Python#
Parameter=#BackendCommand# --tracker
StartInFolder=#@#backend
State=Hide
OutputType=UTF8
Timeout=120000
FinishAction=[!CommandMeasure MeasureScript "Reload(true)"]

; Parameter is set by Watchlist.lua before each run (--add / --remove).
[MeasureTrackerEdit]
Measure=Plugin
Plugin=RunCommand
Program=#Python#
Parameter=#BackendCommand# --tracker
StartInFolder=#@#backend
State=Hide
OutputType=UTF8
Timeout=120000
FinishAction=[!CommandMeasure MeasureScript "Reload(true)"]

[MeasureOpenConfig]
Measure=Plugin
Plugin=RunCommand
Program=#Python#
Parameter=#BackendCommand# --edit-config
StartInFolder=#@#backend
State=Hide

[MeasureRefreshTimer]
Measure=Calc
Formula=1
UpdateDivider=#WatchRefreshSeconds#
OnUpdateAction=[!CommandMeasure MeasureScript "Refresh()"]

[MeasureAddInput]
Measure=Plugin
Plugin=InputText
X=#Padding#
Y=(#Padding# - 3)
W=(#SkinW# - #Padding# * 2)
H=20
FontFace=#FontFace#
FontSize=10
FontColor=#ColorText#
SolidColor=30,33,42,255
StringStyle=Bold
FocusDismiss=1
InputLimit=60
DefaultValue=
Command1=[!SetVariable NewTickers "$UserInput$"][!CommandMeasure MeasureScript "Add()"]

; ============================================================ Styles

[StyleText]
FontFace=#FontFace#
FontColor=#ColorText#
FontSize=9
AntiAlias=1

[StyleRight]
StringAlign=Right

[StyleChart]
LinePath=0,0 | LineTo 1,0
AreaPath=0,0 | LineTo 1,0
AreaGradient=90 | 0,0,0,0 ; 0.0 | 0,0,0,0 ; 1.0
Shape2=Path AreaPath | StrokeWidth 0 | Fill Color 0,0,0,0
Shape3=Path LinePath | StrokeWidth 0 | Stroke Color 0,0,0,0
Shape4=Line 0,0,0,0 | StrokeWidth 0 | Stroke Color 0,0,0,0

[StyleTileSymbol]
FontSize=11
FontWeight=700

[StyleTilePrice]
FontSize=10
FontWeight=600
FontColor=#ColorBody#

[StyleTilePct]
FontWeight=700

[StyleTilePoints]
FontSize=8
FontWeight=600

[StyleRemove]
Shape=Rectangle 0,0,12,12 | Fill Color 0,0,0,1 | StrokeWidth 0
ToolTipText=Remove from watchlist
DynamicVariables=1

; ============================================================ Header

[MeterBackground]
Meter=Shape
Shape=Rectangle 0,0,#SkinW#,(#GridY# + #WatchTileH# * 2 + #WatchGap# + #Padding#),12 | Fill Color #ColorBackground# | StrokeWidth 0

[MeterHeader]
Meter=String
MeterStyle=StyleText
X=#Padding#
Y=#Padding#
FontSize=8
FontWeight=700
FontColor=#ColorAccent#
Text=WATCHLIST

[MeterStatus]
Meter=String
MeterStyle=StyleText | StyleRight
X=(#SkinW# - #Padding# - 22)
Y=#Padding#
FontSize=8
FontColor=#ColorDim#
Text=Loading...

[MeterAdd]
Meter=Shape
X=(#SkinW# - #Padding# - 14)
Y=(#Padding# - 1)
Shape=Rectangle 0,0,14,14,3 | Fill Color #ColorCard# | StrokeWidth 0
Shape2=Line 7,3.5,7,10.5 | StrokeWidth 1.6 | Stroke Color #ColorText# | StrokeStartCap Round | StrokeEndCap Round
Shape3=Line 3.5,7,10.5,7 | StrokeWidth 1.6 | Stroke Color #ColorText# | StrokeStartCap Round | StrokeEndCap Round
ToolTipText=Add stocks (comma-separated, e.g. AMD, TSLA)
LeftMouseUpAction=[!CommandMeasure MeasureAddInput "ExecuteBatch 1"]

[MeterEmpty]
Meter=String
MeterStyle=StyleText
X=#Padding#
Y=(#GridY# + 8)
FontColor=#ColorDim#
Text=No stocks yet. Click + to add some.
Hidden=1

; ============================================================ Tiles
"""

TILE_VARIABLES = """\
Tile{i}X=(#Padding# + ({n} % #WatchColumns#) * (#WatchTileW# + #WatchGap#))
Tile{i}Y=(#GridY# + Trunc({n} / #WatchColumns#) * (#WatchTileH# + #WatchGap#))
Tile{i}RemoveColor=0,0,0,0
"""

SHOW_REMOVE = '[!SetVariable Tile{i}RemoveColor "#ColorDim#"][!UpdateMeter Tile{i}Remove][!Redraw]'
HIDE_REMOVE = '[!SetVariable Tile{i}RemoveColor "0,0,0,0"][!UpdateMeter Tile{i}Remove][!Redraw]'

TILE = """\
[Tile{i}Card]
Meter=Shape
MeterStyle=StyleChart
X=#Tile{i}X#
Y=#Tile{i}Y#
Shape=Rectangle 0,0,#WatchTileW#,#WatchTileH#,8 | Fill Color #ColorCard# | StrokeWidth 0
MouseOverAction={show_remove}
MouseLeaveAction={hide_remove}
Group=Tile{i}
Hidden=1

[Tile{i}Symbol]
Meter=String
MeterStyle=StyleText | StyleTileSymbol
X=(#Tile{i}X# + 9)
Y=(#Tile{i}Y# + 6)
Group=Tile{i}
Hidden=1

[Tile{i}Price]
Meter=String
MeterStyle=StyleText | StyleTilePrice
X=(#Tile{i}X# + 9)
Y=(#Tile{i}Y# + 26)
Group=Tile{i}
Hidden=1

[Tile{i}Pct]
Meter=String
MeterStyle=StyleText | StyleRight | StyleTilePct
X=(#Tile{i}X# + #WatchTileW# - 9)
Y=(#Tile{i}Y# + 25)
Group=Tile{i}
Hidden=1

[Tile{i}Points]
Meter=String
MeterStyle=StyleText | StyleRight | StyleTilePoints
X=(#Tile{i}X# + #WatchTileW# - 9)
Y=(#Tile{i}Y# + 40)
Group=Tile{i}
Hidden=1

[Tile{i}Remove]
Meter=Shape
MeterStyle=StyleRemove
X=(#Tile{i}X# + #WatchTileW# - 19)
Y=(#Tile{i}Y# + 7)
Shape2=Line 2.5,2.5,9.5,9.5 | StrokeWidth 1.5 | Stroke Color [#Tile{i}RemoveColor] | StrokeStartCap Round | StrokeEndCap Round
Shape3=Line 9.5,2.5,2.5,9.5 | StrokeWidth 1.5 | Stroke Color [#Tile{i}RemoveColor] | StrokeStartCap Round | StrokeEndCap Round
MouseOverAction={show_remove}
LeftMouseUpAction=[!CommandMeasure MeasureScript "Remove({i})"]
Group=Tile{i}
Hidden=1
"""


def render() -> str:
    tile_variables = "".join(TILE_VARIABLES.format(i=i, n=i - 1) for i in range(1, MAX_TILES + 1))
    tiles = "\n".join(
        TILE.format(i=i, show_remove=SHOW_REMOVE.format(i=i), hide_remove=HIDE_REMOVE.format(i=i))
        for i in range(1, MAX_TILES + 1)
    )
    text = HEADER.format(max_tiles=MAX_TILES, tile_variables=tile_variables) + "\n" + tiles
    return text.replace("\r\n", "\n").replace("\n", "\r\n")


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_bytes(render().encode("ascii"))
    print(f"Wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
